
development:
  adapter: postgresql
  encoding: unicode
  database: app0907api_development
  pool: 5
  username: app0907api
  password: techno8021

 
test:
  adapter: postgresql
  encoding: unicode
  database: app0907api_test
  pool: 5
  username: app0907api
  password: techno8021

production:
  adapter: postgresql
  encoding: unicode
  database: app0907api_production
  pool: 5
  username: app0907api
  password: techno8021
